### ISSUE TITLE
rappid api returns 404

### ISSUE THREAD

**Issue by fgy58963** [toolswall/TikTok_No_Watermark#1]
Hi,I am trying api on rappid, but it returns 404 error.
![image](https://user-images.githubusercontent.com/3829889/100195273-0c875c80-2f32-11eb-8bde-004a0e2ef5c2.png)

**Comment by toolswall** [comment]
> Hi,I am trying api on rappid, but it returns 404 error.
> ![image](https://user-images.githubusercontent.com/3829889/100195273-0c875c80-2f32-11eb-8bde-004a0e2ef5c2.png)

sorry... configured wrong endpoint，you may try again

**Comment by fgy58963** [comment]
yea, it works. thanks a lot to fix this. Btw, we need grab many video and analysis them to make a trend report. Do you provide source code for sale ? Or rappid API can hold about 30,000 request per day?

**Comment by toolswall** [comment]
> yea, it works. thanks a lot to fix this. Btw, we need grab many video and analysis them to make a trend report. Do you provide source code for sale ? Or rappid API can hold about 30,000 request per day?

No plan for sale yet, as i tested api can hold 30000 per day.

**Comment by fgy58963** [comment]
Thank you, I will use rappid api with 4 account, that may reach about 32000 request per day.

**Comment by toolswall** [comment]
> Thank you, I will use rappid api with 4 account, that may reach about 32000 request per day.

superproject 😀
